apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: scylla-configuration
manifests:
  rawYaml:
    - scylla/k8s/statefulset.yaml
    - scylla/k8s/service.yaml
    - scylla/k8s/job.yaml
    - scylla/k8s/configmap.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: statefulset
    resourceName: scylla-db
    port: 9042
    localPort: 9042
---
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: server
requires:
  - configs:
      - scylla-configuration
manifests:
  rawYaml:
    - server/k8s/deployment.yaml
    - server/k8s/service.yaml
build:
  local:
    concurrency: 0
  artifacts:
    - image: server
      context: .
      docker:
        dockerfile: server/Dockerfile
deploy:
  kubectl: {}
portForward:
  - resourceType: deployment
    resourceName: server
    port: 50051
    localPort: 50051