apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      initContainers:
        - name: wait-for-scylla-db
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get svc scylla-db; do
                echo "Waiting for scylla-db service to be ready"
                sleep 5
              done
              until kubectl wait --for=condition=complete job/scylla-init --timeout=120s; do
                echo "Waiting for scylla-init job to complete"
                sleep 5
              done
      containers:
        - name: server
          image: server
          ports:
            - containerPort: 50051